
GET http://localhost:8080/api/book

###

GET http://localhost:8080/api/book/6334634881d8ae4ba04fbc8e

###

POST http://localhost:8080/api/book
Content-Type: application/json

{
    "title": "バリデーション"
}

###

PATCH  http://localhost:8080/api/book/665d7cc0d7895a1a91daec22
Content-Type: application/json

{
    "title": "バリデーションテスト0"
}

### 

DELETE http://localhost:8080/api/book/6658b48e2bfb288a0863e80a