
GET http://localhost:8080/api/book

###

GET http://localhost:8080/api/book/6334634881d8ae4ba04fbc8e

###

POST http://localhost:8080/api/book
Content-Type: application/json

{
    "title": "バリデーション"
}

###

PATCH  http://localhost:8080/api/book/66583dd0c8326802c181ef12
Content-Type: application/json

{
    "title": "バリデーションテスト"
}

### 

DELETE http://localhost:8080/api/book/6656ac07cc3bb5de5a1f9aee